modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-woodenShears/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-wooden-shears"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="woodenshears" #mandatory
version="1.0.0" #mandatory
displayName="SBM-Wooden Shears" #mandatory
description='''Simple addition of primitive shears made of wood''' #mandatory

[[dependencies.woodenshears]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenshears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"