modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-woodenShears/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-wooden-shears"
authors="BuiltBrokenModding"
license="All rights reserved"

[[mods]] #mandatory
modId="woodenshears" #mandatory
version="1.2.0" #mandatory
displayName="SBM-Wooden Shears" #mandatory
description='''Simple addition of primitive shears made of wood''' #mandatory

[[dependencies.woodenshears]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenshears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"