modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-woodenShears/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-wooden-shears"
authors="BuiltBrokenModding"
license="All rights reserved"

[[mods]] #mandatory
modId="woodenshears" #mandatory
version = "${file.jarVersion}" #mandatory
displayName="SBM-Wooden Shears" #mandatory
description='''Simple addition of primitive shears made of wood''' #mandatory

[[dependencies.woodenshears]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenshears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"