modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-woodenShears/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-wooden-shears"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="woodenshears" #mandatory
version="0.0.1" #mandatory
displayName="SBM-Wooden Shears" #mandatory
description='''Simple addition of primitive shears made of wood''' #mandatory

[[dependencies.woodenshears]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenshears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"